const $=s=>document.querySelector(s);
const esc=v=>{const n=document.createElement("span");n.textContent=String(v??"");return n.innerHTML};
const initialOpinion=`## 사업 및 거래 현황
A기업은 자동차 및 전기차 부품을 제조·판매하는 중견기업으로, 주요 완성차 업체와 안정적인 거래관계를 유지하고 있습니다. 2025년 매출액은 1,680억원으로 전년 대비 12.3% 증가했으며 신규 고객사 수주가 외형 성장의 주요 동력입니다.

## 재무 및 상환능력 분석
2025년 말 부채비율은 108.8%, 유동비율은 152.4%로 단기 유동성은 양호합니다. 영업이익률과 영업활동현금흐름이 개선되고 있으며, 예상 DSCR 1.45배를 감안하면 전반적인 상환능력은 양호한 수준입니다.

## 자금용도 및 상환계획
신청자금은 설비 고도화와 운전자금 보강에 사용될 예정으로 목적이 구체적입니다. 신규 수주에 따른 영업현금 유입을 주된 상환재원으로 제시하고 있으나 만기 집중 위험에 대한 기간 중 모니터링이 필요합니다.

## 주요 위험요인 및 보완사항
전기차 시장 성장 둔화, 고객사 발주 변동, 원자재 가격과 환율 변동이 주요 위험요인입니다. 투자 진행률과 양산 일정, 수주 실적 및 현금흐름을 정기적으로 확인하는 조건이 필요합니다.

## 종합 심사의견
거래처 기반과 개선되는 수익지표, 명확한 자금용도를 고려할 때 여신 취급이 가능할 것으로 판단됩니다. 다만 주요 수주 실적과 현금흐름 모니터링을 여신 조건에 포함하는 것이 타당합니다.`;

const state={caseId:null,conversationId:crypto.randomUUID().replaceAll("-",""),messages:[],attachments:[],sources:[],busy:false,abort:null,versions:[{id:1,text:initialOpinion,createdAt:"초기 의견"}],versionIndex:0,proposal:null,feedbackMode:false,sort:{key:"name",direction:"asc"},selectedSource:null};


const evidenceKeywords={
 "사업":["companies","사업","기업","신용조사"],
 "재무":["financials","재무","현금흐름"],
 "상환":["loans","대출","여신","현금흐름"],
 "위험":["companies","신용","리스크","사업계획"],
 "담보":["담보"],
 "종합":["companies","financials","loans"]
};

function parseOpinion(text){const clean=(text||"").replace(/^```(?:markdown)?|```$/gm,"").trim();const parts=clean.split(/^##\s+/m).filter(Boolean);if(!parts.length)return[{title:"심사의견",body:clean}];return parts.map(part=>{const [title,...lines]=part.split("\n");return{title:title.replace(/^#+\s*/,"").trim(),body:lines.join("\n").trim()}})}
function evidenceIdsFor(title){const matched=Object.entries(evidenceKeywords).find(([label])=>title.includes(label))?.[1]||[];const ids=state.sources.filter(source=>matched.some(keyword=>source.name.toLowerCase().includes(keyword.toLowerCase()))).map(source=>source.id);return (ids.length?ids:state.sources.slice(0,3).map(source=>source.id)).slice(0,4)}
function evidenceSentence(text,title){const ids=evidenceIdsFor(title).join(",");return `<span class="evidence-claim" tabindex="0" data-evidence="${ids}">${esc(text)}</span>`}
function renderOpinionBody(body,title){const lines=body.split("\n"),html=[];let list=null;const closeList=()=>{if(list){html.push(`</${list}>`);list=null}};for(const raw of lines){const line=raw.trim();if(!line){closeList();continue}const heading=line.match(/^###\s+(.+)/);if(heading){closeList();html.push(`<h4>${esc(heading[1])}</h4>`);continue}const bullet=line.match(/^[-*]\s+(.+)/),ordered=line.match(/^\d+[.)]\s+(.+)/);if(bullet||ordered){const next=ordered?"ol":"ul";if(list!==next){closeList();list=next;html.push(`<${list}>`)}html.push(`<li>${evidenceSentence((bullet||ordered)[1],title)}</li>`);continue}closeList();html.push(`<p>${evidenceSentence(line,title)}</p>`)}closeList();return html.join("")}
function renderOpinion(text,{streaming=false}={}){const parts=parseOpinion(text),root=$("#opinionContent");root.innerHTML=parts.map((section,i)=>`<section class="opinion-section"><h3>${esc(section.title)}${streaming?`<span class="section-state ${i===parts.length-1?"writing":"done"}">${i===parts.length-1?"작성 중":"반영 완료"}</span>`:""}</h3>${renderOpinionBody(section.body,section.title)}${streaming&&i===parts.length-1?'<i class="stream-cursor"></i>':""}</section>`).join("");if(streaming)root.scrollTop=root.scrollHeight}
function renderVersion(){const current=state.versions[state.versionIndex],latest=state.versionIndex===state.versions.length-1,prev=$("#previousOpinionVersion"),next=$("#nextOpinionVersion");$("#currentOpinionVersion").textContent=`V${current.id}${latest?" · 최신":""}`;prev.textContent=`‹ V${Math.max(1,current.id-1)}`;prev.disabled=state.versionIndex===0;next.textContent=`V${current.id+1} ›`;next.disabled=latest;renderOpinion(current.text)}
function addMessage(role,text){const a=document.createElement("article"),d=document.createElement("div");a.className=role;if(role==="assistant"){const av=document.createElement("span");av.className="avatar";av.textContent="AI";a.append(av)}d.innerHTML=`<p>${esc(text)}</p>`;a.append(d);$("#conversation").append(a);$("#conversation").scrollTop=$("#conversation").scrollHeight;return a}
function splitAnswer(text,limit=650){const chunks=[];let rest=text.trim();while(rest.length>limit){let cut=Math.max(rest.lastIndexOf("\n\n",limit),rest.lastIndexOf(". ",limit),rest.lastIndexOf("다. ",limit));if(cut<limit*.55)cut=limit;else cut+=cut===rest.lastIndexOf("\n\n",limit)?2:2;chunks.push(rest.slice(0,cut).trim());rest=rest.slice(cut).trim()}if(rest)chunks.push(rest);return chunks}
function chatInline(text){return esc(text).replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>")}
function renderChatMarkdown(text){return text.split("\n").map(line=>{const heading=line.match(/^#{1,4}\s+(.+)/);if(heading)return`<span class="chat-heading">${chatInline(heading[1])}</span>`;const bullet=line.match(/^[-*]\s+(.+)/);if(bullet)return`<span class="chat-list">• ${chatInline(bullet[1])}</span>`;const ordered=line.match(/^(\d+[.)])\s+(.+)/);if(ordered)return`<span class="chat-list">${ordered[1]} ${chatInline(ordered[2])}</span>`;return chatInline(line)||"<br>" }).join("<br>")}
function showAnswerInBubbles(article,text){const chunks=splitAnswer(text),render=(target,index)=>{target.querySelector("p").innerHTML=renderChatMarkdown(chunks[index]);if(index>=chunks.length-1)return;const more=document.createElement("button");more.type="button";more.className="more-answer";more.textContent=`대화 더보기 (${index+1}/${chunks.length})`;more.onclick=()=>{more.remove();const next=addMessage("assistant",chunks[index+1]);render(next,index+1)};target.querySelector("div").append(more)};render(article,0)}
function addDecision(text){const a=addMessage("assistant",text),box=document.createElement("div");box.className="confirm-actions";box.innerHTML='<button class="primary" data-answer="yes">예</button><button data-answer="no">아니오</button><button data-answer="feedback">반영내용 보완</button>';box.onclick=e=>{const answer=e.target.dataset.answer;if(!answer)return;box.remove();if(answer==="yes")applyOpinion();if(answer==="no"){state.proposal=null;addMessage("user","아니오");addMessage("assistant","알겠습니다. 현재 심사의견은 변경하지 않겠습니다.")}if(answer==="feedback"){state.feedbackMode=true;addMessage("user","반영내용 보완");addMessage("assistant","보완하거나 제외할 내용, 또는 원하는 심사의견 카테고리를 입력해 주세요.");$("#messageInput").focus()}};a.querySelector("div").append(box)}
function setBusy(on){state.busy=on;$("#chatForm").classList.toggle("busy",on);$(".apply-row").classList.toggle("busy",on);$("#copyOpinion").disabled=on;$("#saveOpinion").disabled=on;$("#sendButton").textContent=on?"■":"↑";$("#sendButton").classList.toggle("stop",on)}
function conversationContext(){return state.messages.slice(-10).map(m=>`${m.role==="user"?"사용자":"AI"}: ${m.content}`).join("\n")||"추가 대화 없음"}
function screenContext(){const current=state.versions[state.versionIndex]||state.versions.at(-1),selected=state.sources.find(source=>source.id===state.selectedSource);return{current_review_version:current?.id,current_review:current?.text||"",selected_source:selected?{id:selected.id,name:selected.name,type:selected.type,status:selected.status}:null,input_data_count:state.sources.length,pending_attachment_names:state.attachments.map(item=>item.name)}}
function validateCompleteReview(text){const sections=parseOpinion(text);if(text.trim().length<400||sections.length<3)throw Error("완성된 심사의견을 받지 못했습니다. 기존 버전은 유지됩니다.");const titles=sections.map(item=>item.title).join(" ");if(!/(상환|재무)/.test(titles)||!/(위험|리스크|보완)/.test(titles)||!/(종합|최종)/.test(titles))throw Error("필수 심사 섹션이 완성되지 않았습니다. 기존 버전은 유지됩니다.");return text}
function requestProposal(){if(state.busy)return;const userNotes=state.messages.filter(m=>m.role==="user").map(m=>m.content);const categoryNotes=userNotes.filter(v=>/(항목|카테고리|목차|구성|관점|기준)/.test(v));const summary=["현재 대화에서 확인된 추가 정보와 요청사항을 심사의견에 반영합니다.",categoryNotes.length?`요청하신 구성 기준(“${categoryNotes.at(-1)}”)에 맞춰 소제목을 재구성합니다.`:"소제목은 대화의 쟁점에 맞게 재구성하되 여신심사 핵심 판단요소를 유지합니다.","상환능력과 근거 수치, 주요 위험 및 보완조건, 종합 심사의견을 포함합니다."].join("\n");state.proposal={summary,feedback:""};addMessage("user","현재까지 내용 반영");addDecision(`${summary}\n\n이대로 심사의견에 반영할까요?`)}
async function applyOpinion(){if(state.busy||!state.proposal)return;addMessage("user","예, 반영해 주세요.");const progressMessage=addMessage("assistant","확인했습니다. 변경 내용을 새 버전의 심사의견에 반영하고 있습니다…");setBusy(true);$("#opinionProgress").classList.remove("hidden");$("#opinionProgressText").textContent="카테고리와 근거를 구성하는 중…";const pendingId=state.versions.length+1;$("#currentOpinionVersion").textContent=`V${pendingId} · 생성 중`;$("#nextOpinionVersion").disabled=true;$("#previousOpinionVersion").disabled=true;let answer="";try{const prompt=`당신은 기업여신 심사역입니다. 현재 심사의견과 대화 이력을 바탕으로 최종 심사의견 전체를 다시 작성하세요.

[중요 작성 규칙]
- 고정된 목차를 기계적으로 사용하지 말고, 사용자가 대화에서 요청한 카테고리나 현재 핵심 쟁점에 맞춰 소제목을 유연하게 구성합니다.
- 다만 기업여신 심사의 목적을 유지하도록 상환능력과 근거, 주요 위험요인과 보완방안, 최종 종합의견은 반드시 포함합니다.
- 확인되지 않은 사실을 만들지 말고, 미입수 정보는 명시합니다.
- 출력은 각 소제목을 '## 소제목' 형식으로 시작하는 한국어 Markdown 본문만 작성합니다.

[반영안]
${state.proposal.summary}
${state.proposal.feedback?`[사용자 보완요청]\n${state.proposal.feedback}`:""}

[대화]
${conversationContext()}`;answer=await streamLLM([...state.messages,{role:"user",content:prompt}],await attachmentPayloads(),text=>{answer=text;renderOpinion(text,{streaming:true});$("#opinionProgressText").textContent=`V${pendingId} 내용을 실시간 작성 중…`},"review");if(!answer.trim())throw Error("생성된 심사의견이 없습니다.");validateCompleteReview(answer);state.versions.push({id:pendingId,text:answer,createdAt:`${new Date().toLocaleString("ko-KR")} 업데이트`});state.versionIndex=state.versions.length-1;state.proposal=null;state.feedbackMode=false;renderVersion();if(state.attachments.length){state.attachments=[];await loadDataCatalog()}progressMessage.querySelector("p").textContent=`심사의견 V${pendingId} 반영을 완료했습니다. 변경된 소제목과 내용을 왼쪽에서 확인해 주세요.`}catch(e){progressMessage.querySelector("p").textContent=`심사의견 반영 중 오류가 발생했습니다: ${e.message}`;renderVersion()}finally{$("#opinionProgress").classList.add("hidden");setBusy(false)}}
const filePayload=f=>new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok({filename:f.name,mime_type:f.type||"application/octet-stream",data_base64:String(r.result).split(",",2)[1]});r.onerror=no;r.readAsDataURL(f)});
const attachmentPayloads=()=>Promise.all(state.attachments.map(a=>filePayload(a.file)));
async function streamLLM(messages,attachments,onToken,responseMode="chat"){const controller=new AbortController;state.abort=controller;const res=await fetch("/api/v1/chat/completions/stream",{method:"POST",headers:{"Content-Type":"application/json","Accept":"text/event-stream"},signal:controller.signal,body:JSON.stringify({messages,attachments,conversation_id:state.conversationId,case_id:state.caseId,current_review:state.versions[state.versions.length-1].text,response_mode:responseMode,screen_context:screenContext()})});if(!res.ok){let detail=`요청 실패 (${res.status})`;try{const payload=await res.json();if(payload.detail)detail=String(payload.detail)}catch{}throw Error(detail)}if(!res.body)throw Error("서버 응답 스트림을 열 수 없습니다.");const reader=res.body.getReader(),decoder=new TextDecoder;let buffer="",answer="",completed=false;while(true){const{value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array,{stream:!done});const lines=buffer.split("\n");buffer=done?"":lines.pop();for(const raw of lines){const line=raw.trim();if(!line||line.startsWith(":"))continue;const event=JSON.parse(line.startsWith("data:")?line.slice(5).trim():line);if(event.type==="meta")state.conversationId=event.conversation_id;if(event.type==="token"){if(event.replace)answer="";answer+=event.content||"";onToken?.(answer);$("#conversation").scrollTop=$("#conversation").scrollHeight}if(event.type==="done"){completed=true;if(typeof event.message==="string"&&event.message.trim()){answer=event.message;onToken?.(answer)}state.lastStreamMetadata=event.metadata||{}}if(event.type==="error")throw Error(event.detail)}if(done)break}if(!completed)throw Error("응답 스트림이 완료되기 전에 연결이 종료되었습니다. 기존 내용은 유지됩니다.");return answer}
async function sendMessage(text){text=text.trim();const hasAttachments=state.attachments.length>0;if((!text&&!hasAttachments)||(!state.caseId&&state.caseId!==null)||state.busy)return;const attachmentNames=state.attachments.map(item=>item.name),question=text||"첨부한 파일을 분석하고 여신심사에 참고할 핵심 내용을 알려줘.",displayText=text||`첨부파일 ${attachmentNames.join(", ")}을 업로드했습니다.`;addMessage("user",displayText);state.messages.push({role:"user",content:question});$("#messageInput").value="";if(state.feedbackMode){state.feedbackMode=false;state.proposal={...(state.proposal||{summary:"대화 내용을 심사의견에 반영합니다."}),feedback:question};addDecision(`보완 요청을 반영해 다음과 같이 수정하겠습니다.\n\n- ${question}\n- 사용자가 지정한 카테고리를 우선 적용합니다.\n- 상환능력, 근거, 위험 및 보완방안, 종합의견은 심사 필수요소로 유지합니다.\n\n이대로 심사의견에 반영할까요?`);return}setBusy(true);const a=addMessage("assistant",hasAttachments?"첨부파일을 업로드하고 요청사항을 처리 중에 있습니다…":"요청사항을 처리 중에 있습니다…"),p=a.querySelector("p");try{const answer=await streamLLM(state.messages,await attachmentPayloads(),t=>{p.textContent=t},"chat");showAnswerInBubbles(a,answer);state.messages.push({role:"assistant",content:answer});if(state.attachments.length){state.attachments=[];await loadDataCatalog()}}catch(e){if(e.name==="AbortError")p.textContent="응답 생성을 중단했습니다.";else p.textContent=`파일 처리 중 오류가 발생했습니다: ${e.message}`}finally{setBusy(false)}}

function renderFiles(){$("#pendingFiles").innerHTML=state.attachments.map((a,i)=>`<span class="file-chip">▧ ${esc(a.name)} <button data-remove-file="${i}" type="button">×</button></span>`).join("");$("#dataCountBadge").textContent=state.sources.length}
function addFiles(files){for(const file of files){if(state.attachments.some(a=>a.name===file.name))continue;state.attachments.push({name:file.name,file});const ext=file.name.split(".").pop().toUpperCase(),type=file.type.startsWith("image/")?"이미지":ext;state.sources.push({id:state.sources.length?Math.max(...state.sources.map(s=>s.id))+1:1,name:file.name,type,status:"사용자 업로드",file,body:"사용자가 대화창에서 업로드한 원본 자료"})}renderFiles()}
function sortedSources(){const q=$("#dataSearch").value.trim().toLowerCase(),items=state.sources.filter(s=>`${s.name} ${s.type} ${s.status}`.toLowerCase().includes(q)),{key,direction}=state.sort;return items.sort((a,b)=>String(a[key]).localeCompare(String(b[key]),"ko")*(direction==="asc"?1:-1))}
function renderSources(){const items=sortedSources();$("#dataSummary").textContent=`${items.length} variables / ${state.sources.length} total`;$("#dataSourceBody").innerHTML=items.map(s=>`<tr data-source="${s.id}" class="${s.id===state.selectedSource?"selected":""}"><td>${String(s.id).padStart(2,"0")}</td><td>${esc(s.name)}</td><td><span class="type">${esc(s.type)}</span></td><td><span class="status ${s.status.includes("업로드")?"upload":""}">${esc(s.status)}</span></td></tr>`).join("");document.querySelectorAll("[data-sort]").forEach(b=>{b.querySelector("i").textContent=state.sort.key===b.dataset.sort?(state.sort.direction==="asc"?"↑":"↓"):""});renderPreview(state.sources.find(s=>s.id===state.selectedSource))}
function renderPreview(s){const root=$("#sourcePreview");if(!s){root.innerHTML='<div class="preview-empty">행을 선택하면 원천자료를 확인할 수 있습니다.</div>';return}const head=`<header class="preview-head"><div><h3>${esc(s.name)}</h3><span>READ ONLY · ${esc(s.type)} · ${esc(s.status)}</span></div></header>`;if(s.type==="테이블"||s.type==="XLSX"){const columns=s.columns||["값"],rows=s.rows||[];root.innerHTML=head+`<div class="query-meta">SELECT * FROM ${s.type==="테이블"?"information_system":"uploaded_workbook"}.${s.name} LIMIT 100;\n-- ${rows.length} rows returned · read only</div><div class="result-grid"><table><thead><tr>${columns.map(c=>`<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;return}if(s.type==="이미지"&&s.file){const url=URL.createObjectURL(s.file);root.innerHTML=head+`<div class="image-preview"><img src="${url}" alt="${esc(s.name)}"></div>`;return}if(s.type==="PDF"){const url=sourceFileUrl(s);root.innerHTML=head+(url?`<div class="actual-document-preview"><iframe src="${esc(url)}#view=FitH" title="${esc(s.name)} 원본 PDF"></iframe></div>`:`<div class="preview-empty">원본 PDF를 불러올 수 없습니다.</div>`);return}root.innerHTML=head+`<div class="document-preview"><article class="paper"><h2>${esc(s.name)}</h2><p>문서유형: ${esc(s.type)}　자료출처: ${esc(s.status)}</p><h3>원천자료 미리보기</h3><p>${esc(s.body||"업로드 원본 문서의 읽기 전용 미리보기입니다.")}</p><h3>심사 참고사항</h3><p>이 화면은 원천자료 확인용이며 내용을 수정하지 않습니다. AI 답변과 심사의견에 활용된 수치는 반드시 본 자료와 대조할 수 있습니다.</p></article></div>`}
let citationHideTimer;
function sourceDetail(source){return{locator:source.row_count==null?source.type:`${source.row_count}건`,excerpt:source.body||`${(source.columns||[]).join(", ")} 항목을 포함한 ${source.status} 자료`}}
function showCitationPopover(claim){clearTimeout(citationHideTimer);document.querySelectorAll(".evidence-claim.is-active").forEach(node=>node.classList.remove("is-active"));claim.classList.add("is-active");const ids=claim.dataset.evidence.split(",").map(Number),sources=ids.map(id=>state.sources.find(s=>s.id===id)).filter(Boolean),popover=$("#citationPopover");popover.innerHTML=`<header><b>근거자료</b><span>${sources.length}</span></header>${sources.map(s=>{const d=sourceDetail(s);return`<section class="citation-card"><b>${esc(s.name)}</b><p>${esc(d.locator)} · ${esc(d.excerpt)}</p><button type="button" data-open-evidence="${s.id}">원문 보기 ↗</button></section>`}).join("")}`;popover.classList.remove("hidden","flip");state.activeEvidenceIds=ids;const rect=claim.getBoundingClientRect(),width=popover.offsetWidth,height=popover.offsetHeight;let left=rect.right+12;if(left+width>innerWidth-12){left=Math.max(12,rect.left-width-12);popover.classList.add("flip")}let top=Math.min(innerHeight-height-12,Math.max(12,rect.top-height*.25));popover.style.left=`${left}px`;popover.style.top=`${top}px`}
function scheduleCitationHide(){clearTimeout(citationHideTimer);citationHideTimer=setTimeout(()=>{$("#citationPopover").classList.add("hidden");document.querySelectorAll(".evidence-claim.is-active").forEach(node=>node.classList.remove("is-active"))},180)}
function sourceFileUrl(source){return source.file?URL.createObjectURL(source.file):(source.source_url||"")}
function renderPdfEvidence(source){const url=sourceFileUrl(source);return url?`<div class="actual-document-preview"><iframe src="${esc(url)}#view=FitH" title="${esc(source.name)} 원본 PDF"></iframe></div>`:`<div class="preview-empty">원본 PDF를 불러올 수 없습니다. 파일을 다시 첨부해 주세요.</div>`}
function renderTableEvidence(source){const columns=source.columns||["값"],rows=source.rows||[];return`<div class="query-meta">SELECT * FROM information_system.${esc(source.name)} WHERE evidence_linked = true;\n-- linked evidence highlighted · read only</div><div class="table-evidence-view"><table><thead><tr>${columns.map(c=>`<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${rows.map((row,i)=>`<tr class="${i===0?"highlighted":""}">${row.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function renderDocumentEvidence(source,detail){return`<article class="evidence-page"><small>${esc(source.type)} · ${esc(source.status)}</small><h3>${esc(source.name)}</h3><p>본 자료에서 심사의견과 연결된 원문을 확인합니다.</p><p class="evidence-highlight">${esc(detail.excerpt)}<span>심사의견 근거</span></p><p>${esc(source.body||"원천자료의 전후 문맥이 이 영역에 표시됩니다.")}</p></article>`}
function openSourceViewer(sourceId){const ids=state.activeEvidenceIds||[sourceId];state.activeEvidenceIndex=Math.max(0,ids.indexOf(sourceId));renderSourceViewer();$("#citationPopover").classList.add("hidden");$("#sourceViewerDialog").showModal()}
function renderSourceViewer(){const ids=state.activeEvidenceIds||[],source=state.sources.find(s=>s.id===ids[state.activeEvidenceIndex]);if(!source)return;const detail=sourceDetail(source);$("#viewerTitle").textContent=source.name;$("#viewerMeta").textContent=`${source.type} · ${detail.locator} · ${source.status}`;$("#viewerBody").innerHTML=source.type==="PDF"?renderPdfEvidence(source):(source.type==="테이블"||source.type==="XLSX")?renderTableEvidence(source):renderDocumentEvidence(source,detail);$("#previousEvidence").disabled=state.activeEvidenceIndex===0;$("#nextEvidence").disabled=state.activeEvidenceIndex===ids.length-1}
function moveEvidence(delta){const next=state.activeEvidenceIndex+delta,ids=state.activeEvidenceIds||[];if(next>=0&&next<ids.length){state.activeEvidenceIndex=next;renderSourceViewer()}}
async function openDataExplorer(){try{await loadDataCatalog()}catch(error){console.warn(error)}renderSources();$("#dataExplorerDialog").showModal()}
async function saveOpinion(){const text=state.versions[state.versionIndex].text,name=`심사의견_V${state.versions[state.versionIndex].id}.txt`,blob=new Blob([text],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function loadDataCatalog(){const pending=state.sources.filter(source=>source.file&&state.attachments.some(item=>item.file===source.file));const query=state.caseId?`?case_id=${encodeURIComponent(state.caseId)}`:"";const response=await fetch(`/api/v1/poc/data-catalog${query}`,{headers:{"Accept":"application/json"}});if(!response.ok)throw Error(`입력 데이터 현황 조회 실패 (${response.status})`);const catalog=await response.json(),items=Array.isArray(catalog.items)?catalog.items:[];let nextId=items.reduce((max,item)=>Math.max(max,Number(item.id)||0),0)+1;state.sources=[...items,...pending.map(source=>({...source,id:nextId++}))];if(!state.sources.some(source=>source.id===state.selectedSource))state.selectedSource=state.sources[0]?.id??null;renderFiles();if($("#dataExplorerDialog").open)renderSources()}
async function init(){renderVersion();renderFiles();try{const r=await fetch("/api/v1/cases");if(r.ok){const d=await r.json();state.caseId=d.items?.[0]?.id??null}await loadDataCatalog()}catch(e){console.warn("입력 데이터 초기화 실패",e);renderFiles()}}

$("#previousOpinionVersion").onclick=()=>{if(state.versionIndex>0){state.versionIndex--;renderVersion()}};
$("#nextOpinionVersion").onclick=()=>{if(state.versionIndex<state.versions.length-1){state.versionIndex++;renderVersion()}};
$("#copyOpinion").onclick=()=>navigator.clipboard.writeText(state.versions[state.versionIndex].text);
$("#saveOpinion").onclick=saveOpinion;
$("#updateOpinion").onclick=requestProposal;
$("#dataStatusButton").onclick=openDataExplorer;
$("#closeDataExplorer").onclick=()=>$("#dataExplorerDialog").close();
$("#opinionContent").addEventListener("mouseover",e=>{const claim=e.target.closest(".evidence-claim");if(claim)showCitationPopover(claim)});
$("#opinionContent").addEventListener("mouseout",e=>{if(e.target.closest(".evidence-claim"))scheduleCitationHide()});
$("#opinionContent").addEventListener("focusin",e=>{const claim=e.target.closest(".evidence-claim");if(claim)showCitationPopover(claim)});
$("#opinionContent").addEventListener("focusout",scheduleCitationHide);
$("#citationPopover").addEventListener("mouseenter",()=>clearTimeout(citationHideTimer));
$("#citationPopover").addEventListener("mouseleave",scheduleCitationHide);
$("#citationPopover").addEventListener("click",e=>{const button=e.target.closest("[data-open-evidence]");if(button)openSourceViewer(Number(button.dataset.openEvidence))});
$("#closeSourceViewer").onclick=$("#viewerCloseButton").onclick=()=>$("#sourceViewerDialog").close();
$("#previousEvidence").onclick=()=>moveEvidence(-1);
$("#nextEvidence").onclick=()=>moveEvidence(1);
$("#dataSearch").oninput=renderSources;
document.querySelectorAll("[data-sort]").forEach(b=>b.onclick=()=>{const key=b.dataset.sort;if(state.sort.key===key)state.sort.direction=state.sort.direction==="asc"?"desc":"asc";else state.sort={key,direction:"asc"};renderSources()});
$("#dataSourceBody").onclick=e=>{const row=e.target.closest("tr[data-source]");if(row){state.selectedSource=Number(row.dataset.source);renderSources()}};
$("#chatAttach").onclick=()=>$("#chatFile").click();
$("#chatFile").onchange=e=>{addFiles([...e.target.files]);e.target.value=""};
$("#pendingFiles").onclick=e=>{const i=e.target.dataset.removeFile;if(i===undefined)return;const [removed]=state.attachments.splice(Number(i),1);state.sources=state.sources.filter(s=>!(s.file===removed.file));renderFiles()};
$("#chatForm").onsubmit=e=>{e.preventDefault();if(state.busy)state.abort?.abort();else sendMessage($("#messageInput").value)};
$("#messageInput").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#chatForm").requestSubmit()}};
$("#messageInput").addEventListener("paste",event=>{const images=[...(event.clipboardData?.items||[])].filter(item=>item.kind==="file"&&item.type.startsWith("image/")).map((item,index)=>{const blob=item.getAsFile();if(!blob)return null;const extension=(blob.type.split("/")[1]||"png").replace("jpeg","jpg");return new File([blob],`스크린샷_${new Date().toISOString().replace(/[:.]/g,"-")}_${index+1}.${extension}`,{type:blob.type,lastModified:Date.now()})}).filter(Boolean);if(!images.length)return;event.preventDefault();addFiles(images);addMessage("assistant",`클립보드 이미지 ${images.length}개를 첨부했습니다. 메시지를 입력한 뒤 전송해 주세요.`)});
init();
