const $=s=>document.querySelector(s);const esc=v=>{const n=document.createElement("span");n.textContent=v;return n.innerHTML};
const state={caseId:null,conversationId:crypto.randomUUID().replaceAll("-",""),messages:[],files:[],attachments:[],busy:false,abort:null,activeSection:"여신신청정보",pendingOpinion:null};
const sections={
"여신신청정보":{source:"정보계",received:true,fields:[["식별정보_여신신청번호","2026081700124","번호"],["식별정보_신청일자","20260814","일자"],["신청조건_신청금액","5000","백만원"],["신청조건_여신기간","3","년"],["상환조건_상환방식코드","1","코드"]]},
"재무상태표":{source:"정보계",received:true,fields:[["자산_유동자산_현금및현금성자산","1200","백만원"],["자산_비유동자산_유형자산","7400","백만원"],["부채_유동부채_단기차입금","3100","백만원"],["부채_비유동부채_장기차입금","4200","백만원"],["자본_자본금","2000","백만원"],["지표_부채비율","178.2","%"]]},
"포괄손익계산서":{source:"정보계",received:true,fields:[["수익_영업수익_매출액","12800","백만원"],["비용_매출원가_매출원가","9600","백만원"],["이익_영업이익_영업이익","840","백만원"],["이익_당기순이익_당기순이익","510","백만원"]]},
"담보정보":{source:"미등록",received:false,fields:[["담보_평가정보_평가금액","","백만원"],["담보_권리정보_선순위금액","","백만원"]]}
};
for(const s of Object.values(sections)){s.original=Object.fromEntries(s.fields.map(([k,v])=>[k,v]));s.units=Object.fromEntries(s.fields.map(([k,,u])=>[k,u]));s.current={...s.original};s.versions=[{id:1,summary:"상세 화면 최초 생성 · 정보계 원본 기준",source:"시스템",time:"09:00",snapshot:{...s.current}}];s.dirty=new Map()}
const defaultRecognition=name=>`[문서 개요]\n${name} 파일에서 텍스트와 표 데이터를 추출했습니다.\n\n[주요 인식 내용]\n  - 문서명: ${name}\n  - 분석 상태: 완료\n  - 정보계 미반영 자료: 사용자 업로드\n\n[여신심사 관련 인식]\n  첨부자료의 주요 수치와 계약조건을 심사 참고정보로 인식했습니다.\n  원문과 대조하여 정확성을 확인할 필요가 있습니다.\n\n[주의사항]\n  AI가 추출한 작업 사본이며 원본 파일은 변경되지 않습니다.\n\n[세부 내용 계속]\n  문서에 포함된 추가 문장과 표 인식 결과가 이 영역에 계속 표시됩니다.`;
function renderStatus(){const list=$("#dataSectionList");list.innerHTML="";Object.entries(sections).forEach(([name,s])=>{const b=document.createElement("button");b.className="data-row";b.innerHTML=`<strong>${name}</strong><span>${s.source}</span><i class="chip ${s.received?"ready":"missing"}">${s.received?"입수":"미입수"}</i>`;b.onclick=()=>openDetail(name);list.append(b)});const group=document.createElement("div");group.className="attachment-group";group.innerHTML=`<div class="attachment-title"><strong>기타 첨부자료</strong><span>사용자 업로드 ${state.attachments.length}건</span><i class="chip ${state.attachments.length?"ready":"missing"}">${state.attachments.length?"입수":"미입수"}</i></div>`;state.attachments.forEach(a=>{const row=document.createElement("div");row.className="attachment-row";row.innerHTML=`<span title="${esc(a.name)}">▧ ${esc(a.name)}</span><button data-view>보기</button><button data-recognition>에이전트 인식내용</button><button data-delete class="delete" aria-label="삭제">⌫</button>`;row.querySelector("[data-view]").onclick=()=>viewAttachment(a);row.querySelector("[data-recognition]").onclick=()=>openRecognition(a);row.querySelector("[data-delete]").onclick=()=>deleteAttachment(a);group.append(row)});list.append(group)}
function toggleStatus(force){const p=$("#dataStatusPopover"),show=force??p.classList.contains("hidden");p.classList.toggle("hidden",!show);$("#dataStatusButton").setAttribute("aria-expanded",String(show))}
function openDetail(name){state.activeSection=name;toggleStatus(false);$("#detailTitle").textContent=name;const s=sections[name];$("#detailReceipt").textContent=s.received?"● 정보계 원본 있음":"● 정보계 원본 없음";renderDetail();$("#dataDetailDialog").showModal()}
function rowStatus(s,key){if(s.dirty.has(key))return["수정 중","changed"];if(s.current[key]!==s.original[key])return["변경","changed"];return["동일",""]}
function renderDetail(){const s=sections[state.activeSection],body=$("#compareBody");body.innerHTML="";Object.keys({...s.original,...s.current}).forEach(key=>{const [label,cls]=rowStatus(s,key),unit=s.units[key]||"-",tr=document.createElement("tr");tr.className=cls;tr.innerHTML=`<td title="${esc(key)}">${esc(key)} <small>(단위: ${esc(unit)})</small></td><td><input data-key="${esc(key)}" inputmode="decimal" pattern="[0-9.]*" value="${esc(s.current[key]??"")}"></td><td>${esc(s.original[key]||"미입수")}</td><td><span class="status ${cls}">${label}</span></td>`;const input=tr.querySelector("input");input.oninput=e=>{const clean=e.target.value.replace(/[^0-9.]/g,"");if(clean!==e.target.value)e.target.value=clean;editField(key,clean,tr)};body.append(tr)});renderDirty();renderVersions()}
function editField(key,value,tr){const s=sections[state.activeSection];if(!s.dirty.has(key))s.dirty.set(key,s.current[key]??"");s.current[key]=value;if(value===s.dirty.get(key))s.dirty.delete(key);const [label,cls]=rowStatus(s,key);tr.className=cls;tr.lastElementChild.innerHTML=`<span class="status ${cls}">${label}</span>`;renderDirty()}
function renderDirty(){const s=sections[state.activeSection],n=s.dirty.size;$("#dirtyBar").classList.toggle("hidden",!n);$("#dirtyCount").textContent=n;$("#nextVersionHint").textContent=`저장 시 V${s.versions.length+1} 생성`}
function renderVersions(){const s=sections[state.activeSection],list=$("#versionList");$("#versionCount").textContent=s.versions.length;list.innerHTML="";[...s.versions].reverse().forEach((v,i)=>{const row=document.createElement("div");row.className=`version-row ${i===0?"current":""}`;row.innerHTML=`<b>V${v.id}${i===0?' <small>현재</small>':''}</b><span>${esc(v.summary)}</span><span>${esc(v.source)}</span><time>${v.time}</time><div>${i?`<button data-view>보기</button> <button data-restore>이 버전으로 복원</button>`:"-"}</div>`;row.querySelector("[data-view]")?.addEventListener("click",()=>alert(`V${v.id}\n\n${Object.entries(v.snapshot).map(([k,val])=>`${k}: ${val}`).join("\n")}`));row.querySelector("[data-restore]")?.addEventListener("click",()=>restoreVersion(v));list.append(row)})}
function restoreVersion(v){const s=sections[state.activeSection],id=s.versions.length+1;s.current={...v.snapshot};s.dirty=new Map();s.versions.push({id,summary:`V${v.id} 정보로 복원`,source:"사용자 복원",time:now(),snapshot:{...s.current}});markOpinionPending();renderDetail()}
function saveChanges(){const s=sections[state.activeSection];if(!s.dirty.size)return;const n=s.dirty.size,id=s.versions.length+1;s.versions.push({id,summary:`${n}개 항목 직접 수정`,source:"사용자 키인",time:now(),snapshot:{...s.current}});s.dirty=new Map();markOpinionPending();renderDetail()}
function cancelChanges(){const s=sections[state.activeSection];for(const[k,v]of s.dirty)s.current[k]=v;s.dirty=new Map();renderDetail()}
function reimport(){const s=sections[state.activeSection];$("#lastImported").textContent=`최종 입수 ${new Date().toLocaleString("ko-KR")}`;if(!s.received){s.received=true;s.source="정보계";s.original={...s.current};s.versions.push({id:s.versions.length+1,summary:"정보계 데이터 재입수",source:"정보계",time:now(),snapshot:{...s.current}})}renderStatus();renderDetail()}
function viewAttachment(a){const url=URL.createObjectURL(a.file),w=open(url,"_blank");if(!w)alert("팝업 차단을 해제해 주세요.");setTimeout(()=>URL.revokeObjectURL(url),60000)}
function openRecognition(a){state.activeAttachment=a;$("#recognitionFileName").textContent=a.name;$("#recognitionVersion").textContent=`인식내용 V${a.recognitionVersion} · ${a.corrected?"사용자 정정 반영":"분석 완료"}`;$("#recognitionText").textContent=a.recognition;$("#recognitionDialog").showModal()}
function deleteAttachment(a){if(!confirm(`${a.name}을(를) 삭제할까요?\n파일과 현재 에이전트 인식내용이 삭제됩니다.`))return;state.attachments=state.attachments.filter(x=>x!==a);state.files=state.files.filter(x=>x!==a.file);renderFiles();renderStatus();markOpinionPending()}
function addMessage(role,text){const a=document.createElement("article");a.className=role;a.innerHTML=role==="assistant"?`<b>AI</b><p>${esc(text)}</p>`:`<p>${esc(text)}</p>`;$("#conversation").append(a);$("#conversation").scrollTop=$("#conversation").scrollHeight;return a}
function addConfirmation(text,onYes){const a=addMessage("assistant",text),box=document.createElement("div");box.className="confirm-actions";box.innerHTML='<button class="yes">예</button><button>아니오</button>';box.children[0].onclick=()=>{box.remove();onYes()};box.children[1].onclick=()=>{box.remove();addMessage("assistant","변경하지 않았습니다.")};a.append(box)}
function detectChangeRequest(text){if(!/(수정|변경|정정)/.test(text))return false;const file=state.attachments.find(a=>text.includes(a.name));if(file){addMessage("user",text);addConfirmation(`${file.name}의 에이전트 인식내용을 요청하신 내용으로 수정할까요?`,()=>{file.recognition+=`\n\n[사용자 정정 V${file.recognitionVersion+1}]\n${text}`;file.recognitionVersion++;file.corrected=true;addMessage("assistant",`에이전트 인식내용이 수정되었습니다.\n인식내용 V${file.recognitionVersion} 생성\n원본 파일은 변경되지 않습니다.`);markOpinionPending()});return true}const target=Object.entries(sections).flatMap(([name,s])=>Object.keys(s.current).map(k=>[name,s,k])).find(([, ,k])=>(text.includes("신청금액")&&k.includes("신청금액"))||(text.includes("부채비율")&&k.includes("부채비율")));const nums=text.match(/\d+(?:\.\d+)?/g);if(target&&nums?.length){const[name,s,key]=target,raw=nums.at(-1),newVal=text.includes("억원")?String(Number(raw)*100):raw,old=s.current[key];addMessage("user",text);addConfirmation(`현재 작업본의 ${key}을(를) ${old}에서 ${newVal}(으)로 수정할까요?`,()=>{s.current[key]=newVal;const id=s.versions.length+1;s.versions.push({id,summary:`${key} ${old} → ${newVal}`,source:"사용자 확인",time:now(),snapshot:{...s.current}});addMessage("assistant",`수정이 반영되었습니다.\n${key}: ${old} → ${newVal}\n신규 버전 V${id} 생성`);markOpinionPending()});return true}return false}
const filePayload=f=>new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok({filename:f.name,mime_type:f.type||"application/octet-stream",data_base64:String(r.result).split(",",2)[1]});r.onerror=no;r.readAsDataURL(f)});const now=()=>new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"});
function setSending(on,c=null){state.busy=on;state.abort=c;const b=$("#sendButton");b.dataset.mode=on?"stop":"send";b.classList.toggle("stop",on);b.textContent=on?"■":"➤"}
function markOpinionPending(answer=null){if(answer)state.pendingOpinion=answer;$("#opinionUpdateBar").classList.remove("hidden")}
async function streamLLM(messages,attachments,onToken){const c=new AbortController;state.abort=c;const res=await fetch("/api/v1/chat/completions/stream",{method:"POST",headers:{"Content-Type":"application/json","Accept":"text/event-stream"},signal:c.signal,body:JSON.stringify({messages,attachments,conversation_id:state.conversationId,case_id:state.caseId,current_review:$("#opinionContent").innerText})});if(!res.ok||!res.body)throw Error(`요청 실패 (${res.status})`);const reader=res.body.getReader(),dec=new TextDecoder;let buf="",answer="",final=null;while(true){const{value,done}=await reader.read();buf+=dec.decode(value||new Uint8Array,{stream:!done});const lines=buf.split("\n");buf=done?"":lines.pop();for(const rawLine of lines){const line=rawLine.trim();if(!line||line.startsWith(":"))continue;const payload=line.startsWith("data:")?line.slice(5).trim():line;const e=JSON.parse(payload);if(e.type==="meta")state.conversationId=e.conversation_id;if(e.type==="token"){answer=e.replace?e.content:answer+e.content;onToken?.(answer)}if(e.type==="done")final=e;if(e.type==="error")throw Error(e.detail)}if(done)break}return final?.message||answer}
async function sendMessage(text){if(!state.caseId||!text.trim()||state.busy)return;if(detectChangeRequest(text)){$("#messageInput").value="";return}setSending(true,new AbortController);addMessage("user",text.trim());state.messages.push({role:"user",content:text.trim()});$("#messageInput").value="";const pending=addMessage("assistant","자료를 조회하고 있습니다…"),p=pending.querySelector("p");try{const payloads=await Promise.all(state.attachments.map(a=>filePayload(a.file)));const answer=await streamLLM(state.messages,payloads,t=>p.textContent=t);p.textContent=answer;state.messages.push({role:"assistant",content:answer});markOpinionPending(answer)}catch(e){if(e.name==="AbortError"){if(p.textContent==="자료를 조회하고 있습니다…")pending.remove()}else p.textContent=`연결 오류: ${e.message}`}finally{setSending(false)}}
async function updateOpinion(){if(state.busy)return;setSending(true,new AbortController);const b=$("#updateOpinion");b.disabled=true;b.textContent="업데이트 중…";try{const prompt="현재 정보계 원본, 작업본 변경사항, 에이전트 인식내용, 사용자 첨부자료와 대화 전체를 반영하여 여신 심사의견을 5개 이상 카테고리로 새로 작성하세요. 데이터가 있는 카테고리는 각각 3문장 이상, 미입수 카테고리는 간단한 미입수 안내만 작성하세요.";const context=state.attachments.map(a=>`[${a.name} 인식내용 V${a.recognitionVersion}]\n${a.recognition}`).join("\n\n");const answer=await streamLLM([...state.messages,{role:"user",content:`${prompt}\n\n${context}`}],await Promise.all(state.attachments.map(a=>filePayload(a.file))));$("#opinionContent").innerText=answer;$("#opinionUpdated").textContent="방금 업데이트됨";state.pendingOpinion=null;$("#opinionUpdateBar").classList.add("hidden")}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent="✧ 심사의견 업데이트";setSending(false)}}
function renderFiles(){$("#pendingFiles").innerHTML=state.files.map(f=>`<span>▧ ${esc(f.name)}</span>`).join("")}
async function saveOpinion(){const text=$("#opinionContent").innerText,name=`심사의견_${$("#loanNumber").textContent}.txt`;if(window.showSaveFilePicker){const h=await showSaveFilePicker({suggestedName:name,types:[{description:"텍스트 파일",accept:{"text/plain":[".txt"]}}]});const w=await h.createWritable();await w.write(text);await w.close()}else{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}
async function init(){renderStatus();const r=await fetch("/api/v1/cases"),d=await r.json(),item=d.items[0];if(item){state.caseId=item.id;$("#companyName").textContent=item.company_name}}
$("#dataStatusButton").onclick=()=>toggleStatus();$("[data-close-status]").onclick=()=>toggleStatus(false);$("#saveChanges").onclick=saveChanges;$("#cancelChanges").onclick=cancelChanges;$("#reimportButton").onclick=reimport;$("#downloadOriginal").onclick=()=>{const s=sections[state.activeSection],a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(s.original,null,2)],{type:"application/json"}));a.download=`${state.activeSection}_정보계원본.json`;a.click()};$("#copyOpinion").onclick=()=>navigator.clipboard.writeText($("#opinionContent").innerText);$("#saveOpinion").onclick=()=>saveOpinion().catch(e=>alert(e.message));$("#copyRecognition").onclick=()=>navigator.clipboard.writeText($("#recognitionText").innerText);$("#updateOpinion").onclick=updateOpinion;$("#chatAttach").onclick=()=>$("#chatFile").click();$("#chatFile").onchange=e=>{for(const f of e.target.files){if(!state.attachments.some(a=>a.name===f.name))state.attachments.push({name:f.name,file:f,recognition:defaultRecognition(f.name),recognitionVersion:1,corrected:false})}state.files=[...e.target.files];renderFiles();renderStatus();markOpinionPending()};$("#chatForm").onsubmit=e=>{e.preventDefault();if($("#sendButton").dataset.mode==="stop")state.abort?.abort();else sendMessage($("#messageInput").value)};$("#messageInput").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#chatForm").requestSubmit()}};init().catch(e=>addMessage("assistant",`초기화 오류: ${e.message}`));
